In [4]:
import numpy as np #importa a biblioteca usada para trabalhar com vetores e matrizes
import pandas as pd #importa a biblioteca usada para trabalhar com dataframes
import util
from scipy.sparse import bsr_matrix

import svmutil
from svmutil import svm_read_problem
from svmutil import svm_problem
from svmutil import svm_parameter
from svmutil import svm_train
from svmutil import svm_predict
from svmutil import svm_save_model

#importa o arquivo e extrai as features
Xfeatures, Y = util.extract_features('everything.csv', rep='ngrams',n=3)
vocab = util.extract_vocab('everything.csv', rep='ngrams',n=3)

model = svm_train(Y, bsr_matrix(Xfeatures), '-q -c %f -t %d -g %f' %(0.25, 1, 0.125))

['lol' 'ol' 'atl' 'tle' 'lea']
['lol' 'ol' 'atl' 'tle' 'lea']


In [10]:
pd.DataFrame(vocab).to_csv('vocab.csv', index=False, header=False)
svm_save_model('libsvm.model', model)

In [6]:
p_labs, p_acc, p_vals = svm_predict(Y, bsr_matrix(Xfeatures), model)

print((p_labs == Y) / len(Y))


Accuracy = 99.2063% (2750/2772) (classification)
[0.00036075 0.00036075 0.00036075 ... 0.00036075 0.00036075 0.00036075]
[1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]


In [7]:
print(p_labs[:10])
print(Y[:10])

[1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
[1 0 0 1 0 1 0 1 0 1]


In [9]:
print(np.argwhere(Xfeatures[1] > 0))

[[  27]
 [ 265]
 [ 431]
 [1083]
 [1362]
 [1817]
 [2303]
 [3327]]
